vich_uploader:
    db_driver: orm

    mappings:
        imagen_file:
            uri_prefix: /uploads/images/users
            upload_destination: '%kernel.project_dir%/public/uploads/images/users'
            namer: vich_uploader.namer_hash
            delete_on_update: true
